I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 233, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 9, in script
    $ renpy.time(2)
  File "game/splash.rpy", line 9, in <module>
    $ renpy.time(2)
TypeError: 'module' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 233, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 9, in script
    $ renpy.time(2)
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/splash.rpy", line 9, in <module>
    $ renpy.time(2)
TypeError: 'module' object is not callable

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Мастер фантазий или мир без котов Pre-Alpha 1.0
Wed Jun 15 15:48:00 2022
