I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 233, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 11, in script
    show logo with dissolve(1)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 233, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/splash.rpy", line 11, in script
    show logo with dissolve(1)
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3676, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Мастер фантазий или мир без котов Pre-Alpha 1.0
Wed Jun 15 16:21:00 2022
